template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "kala1399"
__REPO__ = "lang-kal"
__UND2C__ = "kl"
__UNDEFINED__ = "Kalaallisut"
__UND__ = "kal"
