template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "kala1399"
__REPO__ = "lang-kal"
__UND2C__ = "kl"
__UNDEFINED__ = "Kalaallisut"
__UND__ = "kal"
