template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "kala1399"
__REPO__ = "lang-kal"
__UND2C__ = "kl"
__UNDEFINED__ = "Kalaallisut"
__UND__ = "kal"
